### ISSUE TITLE
Provide example data set for a token of interest

### ISSUE THREAD

**Issue by emazurek** [Great-Hill-Corporation/tokenomics#2]
This data set can be in any format and can be incomplete. Just looking for something to play around with.

**Comment by tjayrush** [comment]
Have you downloaded and compiled the quickBlocks repo? https://github.com/Great-Hill-Corporation/quickBlocks/blob/develop/src/other/install/INSTALL.md

Do that first, then add the ./bin to your path and then you should be able to run `getTrans` and get the help screen.

From there, `cd` into the folder called ./monitors in this repo and run this command:

    cat etherTip.txt  | cut -f1-2 | tr '\t' '.' | sed 's/ //g' >data.txt

then

    getTrans --file:data.txt --verbose

and you should get all of the transactions on the ethereum tip jar since its inception as JSON data.

**Note:** The JSON won't be valid because the transactions won't be comma-separated nor surrounded by square brackets, but you can mess around with that. This is just a temporary way to get you data.

**Comment by emazurek** [comment]
Thanks Jay. Thinking I'll need to run a parity node for this.

**Comment by tjayrush** [comment]
Maybe not. The only thing that won't work is traces. The `getTrans` doesn't look at traces, so it should work on `geth`.  Plus--I wouldn't mind learning what happens with `geth` just as an experiment.

**Comment by emazurek** [comment]
Running `getTrans` while my geth node is running produces an error:


	Warning: The request to the Ethereum node resulted in
	following error message: Couldn't connect to server.
	It is impossible for QuickBlocks to proceed. Quitting...

**Comment by tjayrush** [comment]
How do you start `geth`? Are you enabling the RPC? (It's on by default with Parity).

Let's use this opportunity to debug using QuickBlocks with `geth`.

**Comment by emazurek** [comment]
Thanks Jay, starting geth with `geth --rpc` enables the RPC and lets me run commands with QuickBlocks!
